"""
gravnet constants"""
IMAGE_PATTERN_VIS = "EUC_MER_BGSUB-MOSAIC-VIS_TILE"
IMAGE_PATTERN_G = "EUC_MER_BGSUB-MOSAIC-.*-G_TILE"
IMAGE_PATTERN_R = "EUC_MER_BGSUB-MOSAIC-.*-R_TILE"
IMAGE_PATTERN_I = "EUC_MER_BGSUB-MOSAIC-.*-I_TILE"
IMAGE_PATTERN_Z = "EUC_MER_BGSUB-MOSAIC-.*-Z_TILE"
IMAGE_PATTERN_NISP_H = 'EUC_MER_BGSUB-MOSAIC-NIR-H_TILE'
IMAGE_PATTERN_NISP_J = 'EUC_MER_BGSUB-MOSAIC-NIR-J_TILE'
IMAGE_PATTERN_NISP_Y = 'EUC_MER_BGSUB-MOSAIC-NIR-Y_TILE'
CATALOG_PATTERN = 'EUC_MER_FINAL-CAT_TILE'
